{{- if not .Values.auth.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "ito-backend.fullname" . }}-auth
  labels:
    {{- include "ito-backend.labels" . | nindent 4 }}
type: Opaque
data:
  admin-token: {{ .Values.auth.adminToken | b64enc | quote }}
  token-seed: {{ .Values.auth.tokenSeed | b64enc | quote }}
{{- end }}
